" .vimrc for mutt
" $Id$

source ~/.vimrc

set nobackup
set nohlsearch
set textwidth=70

map _c mm1GSFrom: Christoph Berg <cb@cs.uni-sb.de><esc>G4kdG:r ~/.signature.cs<cr>`m
map _h mm1GSFrom: Christoph Berg <cb@heim-d.uni-sb.de><esc>G4kdG:r ~/.signature<cr>`m
map _7 mm1GSFrom: Christoph Berg DF7CB <df7cb@darc.de><esc>G4kdG:r ~/.signature.df7cb<cr>`m
