#!/bin/bash

for agent in $SSH_AUTH_SOCK ssh-agent-*; do
  case $agent in *.pid) continue ;; esac
  [ -t 1 ] && echo -ne "\e[32m"
  echo "$agent:"
  [ -t 1 ] && echo -ne "\e[0m"
  SSH_AUTH_SOCK=$agent ssh-add -l
done
