#!/bin/sh -e

cd $HOME/.priv

DOMAIN=$(for f in *@*.pub ; do
	echo $(basename $f .pub)
done | wmiimenu)

[ "$DOMAIN" ] || exit 1

if ! ssh-add -l | grep -q $DOMAIN ; then
	ssh-add $DOMAIN < /dev/null
fi

case $DOMAIN in
	*credativ*)
	for host in gauss.credativ.com burns.credativ.lan bsi-freq ; do
		ssh -Nf $host &
	done
	;;
esac
