#!/bin/sh

# wmiir read /bar | sed -e 's/.* /\/bar\//' | grep _ | xargs -n 1 wmiir remove

create_bar ()
{
	wmiir remove /bar/$1 2>/dev/null
	wmiir create /bar/$1
	echo -n "$2" | wmiir write /bar/$1/colors
}

create_bar 00_dummy '#000000 #666666 #777777'

create_bar 10_log '#000000 #88b0ff #a0f0f0'
( tail -n 3 -Fq $HOME/.xsession-errors /var/log/syslog |
	while read line ; do
		case $line in
			*postfix/qmgr*|*postfix/local*|*last?message?repeated*) ;;
			*postfix/*) echo -n $line ; sleep 0.2 ;;
			*) echo -n $line ; sleep 1.4 ;;
		esac
	done |
	wmiir write /bar/10_log/data ) &

if [ -d $HOME/mail/IN ] ; then
	create_bar 20_mail '#000000 #d0a020 #d0d044'
	( $HOME/.wmii-3/mail | wmiir write /bar/20_mail/data ) &
fi

create_bar 30_timer '#000000 #88b0ff #a0f0f0'
( $HOME/.wmii-3/timer | wmiir write /bar/30_timer/data ) &

create_bar 40_load '#000000 #b0dd88 #a0f080'
( while true
do
	echo -n `uptime | sed 's/.*://; s/,//g'`
	sleep 5
done | wmiir write /bar/40_load/data ) &

if [ -d /proc/acpi/battery ] ; then
	create_bar 50_battery
	( $HOME/.wmii-3/battery | wmiir write /bar/50_battery/data ) &
fi

create_bar 60_clock '#000000 #b088ff #f0a0f0'
( while true
do
	echo -n `date '+%1e. %b %H:%M:%S'`
	sleep 1
done | wmiir write /bar/60_clock/data ) &

BDAY="`$HOME/.wmii-3/vcard-today $HOME/.priv/addressbook.vcf`"
if [ "$BDAY" ] ; then
	create_bar 70_birthday '#000000 #dd0000 #ff0000'
	echo -n "$BDAY" | wmiir write /bar/70_birthday/data
fi
