#!/usr/bin/perl -w

use Getopt::Std;

($opt_1, $opt_a, $opt_b, $opt_e, $opt_t) = ();
getopts('1abeht:');

$twocolumn = 'twocolumn,';
$twocolumn = '' if $opt_1;

$directorystyle = "address";
$title = $opt_t || "Adressen";
if($opt_a) {
	$directorystyle = "email-alias";
}
if($opt_b) {
	$directorystyle = "birthday";
	$title = "Geburtstage";
}
if($opt_e) {
	$directorystyle = "email";
	$title = "Email-Adressen";
}
if($opt_h) {
	$directorystyle = "address-html";
}

if(!@ARGV) {
	@ARGV = <*.bib>;
}

map { s/\.bib$// } @ARGV;
$bibfiles = join ",", @ARGV;

open A, ">addr.tex" or die "addr.tex: $!";

print A '\documentclass['. $twocolumn. '12pt]{article}
\usepackage{times,isolatin1,german}
%\usepackage[split,break]{directory}
\usepackage[split]{directory}
%\usepackage{addr-marvo}

\setlength{\hoffset}{-1in}
\setlength{\voffset}{-1in}
\setlength{\oddsidemargin}{2cm}
\setlength{\topmargin}{2cm}
\setlength{\headheight}{0pt}
\setlength{\headsep}{0pt}
\setlength{\textwidth}{17cm}
\setlength{\textheight}{25.7cm}
\setlength{\dirindent}{1em}

\renewcommand{\dirand}{und}
% formats
\renewcommand{\Dirbirthday}[2]{#1.#2.}
\renewcommand{\Dirbirthyear}[1]{#1}
\renewcommand{\Diremail}[1]{#1}
\renewcommand{\Dirurl}[1]{#1}
%\renewcommand{\Dirheader}[1]{\item\hspace{-\dirindent}\textbf{\MakeUppercase{#1}}}
%\renewcommand{\Dirheader}[1]{
%  \item\hspace{-\dirindent}
%  {\centerline{\textbf{\MakeUppercase{#1}}}}
%}
\renewcommand{\Dirheader}[1]{%
  \vfill%\eject%
  \item\hspace{-\dirindent}%
  {\rule{3cm}{2pt} \MakeUppercase{\large #1} \rule{3cm}{2pt}}%
}
\renewcommand{\Dirbirthday}[2]
{#1.~{\ifcase #2\or Januar\or Februar\or März\or April%
	\or Mai\or Juni\or Juli\or August\or September%
	\or Oktober\or November\or Dezember\fi}
}

\begin{document}

\section*{' .$title. '}

\nodir{*}

\directorystyle{' .$directorystyle. '}
\directory{' .$bibfiles. '}

\end{document}
';

close A;

if ($opt_a) {
	system("make aliases");
} elsif ($opt_h) {
	system("make addr.html");
} else {
	system("make");
}
