#!/usr/bin/perl -w
# $Id$

# convert addressbook database to .html

use lib '.';
use addressbook;

print "<dl>\n";
while(<>) {
	addr_get_line($_);

	print "<dt>$vorname $nachname\n";
	print "<dd>\n";
	print "$strasse<br>\n" if $strasse;
	print "$land-" if $land;
	print "$plz $ort<br>\n" if $plz or $ort;
	foreach (split /,\s*/, $email) {
		print "email: <a href=$_>$_</a><br>\n";
	}
	foreach (split /,\s*/, $www) {
		print "www: <a href=http://$_>$_</a><br>\n";
	}
}
print "</dl>\n";
print "<small>Stand: ". scalar(localtime) ."</small>\n";
