#!/usr/bin/perl -w
# $Id$

# convert addressbook database to BibTeX/directory.sty

use strict;
use lib '.';
use addressbook;

my $p;
while(<>) {
	my $f = addressbook::addr_get_line($_);
	#print "\@Person{$vorname.$nachname,\n";
	$p++;
	print "\@Person{p$p,\n";
	print " name = {", join(", ", grep $_, ($f->{nachname}, $f->{zusatz}, $f->{vorname})), "},\n";
	printf " birthday = {%02d %02d},\n", $f->{geb_tag}, $f->{geb_mon} if $f->{geb_tag} or $f->{geb_mon};
	print " birthyear = {$f->{geb_jahr}},\n" if $f->{geb_jahr};
	print " p.address = {", join(", ", grep $_, ($f->{strasse},$f->{land},$f->{plz},$f->{ort})), "},\n";
	print " p.phone = {$f->{tel_priv}},\n" if $f->{tel_priv};
	print " w.phone = {$f->{tel_arbeit}},\n" if $f->{tel_arbeit};
	print " p.email = {$f->{email}},\n" if $f->{email};
	print "}\n\n";
}
