#!/usr/bin/perl -w
# $Id$

# convert addressbook database to mutt aliases

use strict;
use lib '.';
use addressbook;

my %MAIL;
while(<>) {
	my $f = addressbook::addr_get_line($_);
	next unless $f->{email};
	foreach (split /,\s*/, $f->{email}) {
		/(.+)@/;
		if(exists $MAIL{"\L$1"}) {
			die if exists $MAIL{$_};
			$MAIL{$_} = "$f->{vorname} $f->{nachname} <$_>";
		} else {
			$MAIL{"\L$1"} = "$f->{vorname} $f->{nachname} <$_>";
		}
	}
}

foreach (sort keys %MAIL) {
	print "alias $_ $MAIL{$_}\n";
}
