#!/usr/bin/perl -w
# $Id$

use strict;
use lib '.';
use addressbook;

my $exit = 0;

sub check {
	my $field = shift;
	my $regexp = shift;
	return if $$field eq "";	# any field may be empty
	return if $$field =~ /^($regexp)$/; # check field
	print "line $.: malformated field $field: $$field, should match $regexp\n";
	print "line $.: $_";
	$exit = 1;
}

my ($old_nachname, $old_vorname) = ("", "");
my %K;

while(<>) {
	my $f = addressbook::addr_get_line($_);
	if(($old_nachname gt $f->{nachname}) or ($old_nachname eq $f->{nachname} and $old_vorname gt $f->{vorname})) {
		print "line $.: out-of-order, file is not sorted\n";
		print "line $.: $_";
	}
	$f->{geburtstag} =~ /^(\d+\.\d+\.)?\d*$/ or warn "Geburtstag $f->{vorname} $f->{nachname}: $f->{geburtstag}";
	($old_nachname, $old_vorname) = ($f->{nachname}, $f->{vorname});
	if($f->{kategorie}) {
		my @k = split /, */, $f->{kategorie};
		foreach my $k (@k) {
			$K{$k}++;
		}
	} else {
		$K{"(keine)"}++;
	}
}

foreach(sort keys %K) {
	print "$_: $K{$_} ";
}
print "\n";

exit $exit;
