#!/usr/bin/perl -w
# $Id$

# convert addressbook database to Geburtstage

use strict;
use lib '.';
use addressbook;

# plan kann keine Jahre vor 1970 :-/
my $y = (localtime)[5] + 1900;

while(<>) {
	my $f = addressbook::addr_get_line($_);
	next unless $f->{geb_tag};
	$f->{geb_jahr} = " *". ($f->{geb_jahr} % 100) if $f->{geb_jahr};
	my $z = $f->{zusatz} ? "$f->{zusatz} " : "";

	print "$f->{geb_mon}/$f->{geb_tag}/$y  99:99:99  0:0:0  0:0:0  0:0:0  ---------- 0 0\n";
	print "R\t0 0 0 0 1\n";
	print "N\t$z$f->{vorname} $f->{nachname}$f->{geb_jahr}\n";
}

#1/13/2000  99:99:99  0:0:0  0:0:0  0:0:0  ---------- 0 0
#R	0 0 0 0 1
#N	Elke Berg
