#!/usr/bin/perl -w
# $Id$

# convert addressbook database to mailing list

use strict;
use lib '.';
use addressbook;

my $kat = shift || "";

while(<>) {
	my $f = addressbook::addr_get_line($_);
	next unless $f->{kategorie} =~ /\b$kat\b/;
	next unless $f->{email};
	foreach (split /,\s*/, $f->{email}) {
		print "$f->{vorname} $f->{nachname} <$_>\n";
	}
}
