# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.download.defaultFolder", "/home/cb");
user_pref("browser.download.lastDir", "/home/cb");
user_pref("browser.download.progressDnldDialog.keepAlive", false);
user_pref("browser.download.save_converter_index", 1);
user_pref("browser.preferences.lastpanel", 0);
user_pref("browser.startup.homepage", "http://www2.df7cb.de/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.6");
user_pref("dom.disable_window_flip", true);
user_pref("dom.disable_window_move_resize", true);
user_pref("dom.disable_window_open_feature.status", true);
user_pref("dom.disable_window_status_change", true);
user_pref("font.default", "sans-serif");
user_pref("font.name.monospace.x-western", "monospace");
user_pref("font.name.sans-serif.x-western", "sans-serif");
user_pref("font.name.serif.x-western", "serif");
user_pref("font.size.fixed.x-western", 14);
user_pref("intl.accept_languages", "de-de, de, en");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, EUC-JP, KOI8-R, us-ascii, ISO-8859-15");
user_pref("languagemenu.custom1.data", "de-de, de, en");
user_pref("languagemenu.custom1.label", "German (Germany)  ");
user_pref("languagemenu.custom2.data", "en, en-us");
user_pref("languagemenu.custom2.label", "Default");
user_pref("languagemenu.custom3.data", "fr-fr, fr, en");
user_pref("languagemenu.custom3.label", "French (France)");
user_pref("network.image.imageBehavior", 0);
user_pref("network.proxy.http", "router.df7cb.de");
user_pref("network.proxy.http_port", 3128);
user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.1, .df7cb.de");
user_pref("network.proxy.ssl", "router.df7cb.de");
user_pref("network.proxy.ssl_port", 3128);
user_pref("network.proxy.type", 1);
user_pref("prefs.converted-to-utf8", true);
user_pref("privacy.popups.firstTime", false);
user_pref("security.OCSP.URL", "");
user_pref("security.OCSP.signingCA", "Builtin Object Token:Verisign Class 1 Public Primary OCSP Responder");
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("update_notifications.provider.0.last_checked", 1082889054);
user_pref("wallet.caveat", true);
