#!/usr/bin/perl -w

while (<>) {
	if (/^(user_pref\("adblock\.patterns",) "(.*)"\)/) {
		print "$1\n \"";
		my @patterns = split / /, $2;
		print join ("\n ", sort @patterns);
		print "\");\n";
	}
	if (/^user_pref\("guc\./) {
		print;
	}
}
