#!/usr/bin/perl -w

use strict;

$ENV{LC_MESSAGES} = 'C';

my ($capstate, $state, $rate, $cap);
my $full_cap = 1000;
my $temp;

$| = 1;

system "wmiir remove /rbar/status 2> /dev/null && sleep 1";
system "echo \"$ENV{WMII_NORMCOLORS}\" | wmiir create /rbar/status";

open F, "/proc/acpi/battery/BAT1/info" or warn;
while (<F>) {
	if (/^last full capacity:\s+(\d+)/) {
		$full_cap = $1;
	}
}
close F;

do {
	open F, "/proc/acpi/battery/BAT1/state" or warn;
	while (<F>) {
		if (/^capacity state:\s+(.+)/) {
			$capstate = $1;
		} elsif (/^charging state:\s+(.+)/) {
			$state = $1;
		} elsif (/^present rate:\s+(\d+)/) {
			$rate = $1 || 0.01;
		} elsif (/^remaining capacity:\s+(\d+)/) {
			$cap = $1;
			#$cap_str = sprintf "%.1fAh", $1/1000;
		}
	}
	close F;

	open F, "/proc/acpi/thermal_zone/THRM/temperature" or warn;
	while (<F>) {
		if (/^temperature:\s+(\d+)/) {
			$temp = $1;
		}
	}
	close F;

	my $cap_str = sprintf "%.1f%%", 100 * $cap / $full_cap;
	my $bat_file = $state ne "charged" ? sprintf(" \%dmin", 60*$cap/$rate) : "";
	my $capstate_str = $capstate ne "ok" ? "$capstate " : "";

	open L, "/proc/loadavg";
	my $load = <L>;
	chomp $load;
	$load =~ s! \d*/.*!!;
	close L;

	open I, "ifconfig |";
	my $dev;
	my @addr;
	while (<I>) {
		$dev = $1 if /^(\S+)/;
		if ($dev =~ /^eth[14]/) {
			push @addr, $1 if /inet addr:(\S+)/;
		}
	}
	close I;
	my $addr = join ' ', @addr;

	open W, "| wmiir write /rbar/status";
	print W "$capstate_str$state $cap_str$bat_file | ${temp}°C | $load | $addr\n"
		or exit;
	close W;

	if ($capstate eq "critical" and $state ne "charging") {
		system "xmessage 'Battery critical. Will hibernate in 60s.' &";
		sleep 60;
		system "sudo hibernate";
		sleep 10;
		wait;
	}

	sleep 5;
} while (1);
