#!/usr/bin/perl -w

use strict;
use POSIX;

$| = 1;
my $bar = "/rbar/xclock";

system "wmiir remove $bar 2> /dev/null && sleep 1";
system "echo \"$ENV{WMII_FOCUSCOLORS}\" | wmiir create $bar";

do {
	my $date = POSIX::strftime ("KW %V %a %e. %b %H:%M:%S", localtime);

	open W, "| wmiir write $bar" or exit;
	print W "$date\n" or exit;
	close W;
	sleep 1;
} while (1);
