#!/bin/sh

if [ "${ADT:-}" = "skip" ]; then
	echo "Skipping autopkgtests (ADT is set)"
	exit 0
fi

cd /tmp/buildd/*/debian/..

if [ ! -f debian/tests/control ]; then
	echo "Package does not have autopkgtest support, debian/tests/control is missing"
	exit 0
fi

if [ ! -f debian/files ]; then
	echo "Package source is not built, debian/files is missing"
	exit 1
fi

set -ex

#set -- /tmp/adt-*/
#TMPADT="$1"
#if [ ! -d "$TMPADT" ]; then
#	echo "Didn't find any /tmp/adt-*/ directory. It should have been created before invoking cowbuilder."
#	ls -al /tmp
#	exit 1
#fi

# environment variable for postgresql-common testsuite
export PG_UMASKS="077"

apt-get install -y autopkgtest apt-utils pbuilder newpid

## install our binaries to make sure they aren't pulled from the distribution
## (problem seen with autopkgtest 2.6 on lucid)
#if ! debi; then
#	apt-get install -f -y
#	debi
#fi

#mkdir -p "$TMPADT/out"
binaries=$(awk '/\.deb / { print "--binary ../" $1 }' debian/files | xargs)

# launch adt-run in a new PID namespace so several testsuites can run in parallel
#newpid adt-run --tmp-dir $TMPADT/out --summary $TMPADT/summary \#
newpid adt-run \
	$binaries --built-tree $PWD --- adt-virt-null || EXIT=$?

/bin/bash < /dev/tty > /dev/tty 2> /dev/tty

# 4 means some test failed, exit 0 here and let adtsummary2junit report the failure
[ ${EXIT:-0} = 4 ] && exit 0
exit ${EXIT:-0}
